export default {
    path:"/movie",
    component:()=>import("views/movie"),
    name:"movie",
    //重定向
    redirect:"/movie/movieBody",
    children:[
        {
            path:'movieBody',
            component:()=>import("components/movieBody/index.vue"),
            name:"moviebody"
        },
        {
            path:'moviecomming',
            component:()=>import("components/movieComming/index.vue"),
            name:"moviecomming"
        }
    ]
}